version: '3.8'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "7080:80"
      - "7081:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - frontend-admin

  backend:
    image: msoftsantana/seven-board-backend:latest
    container_name: 7board-backend
    restart: unless-stopped
    environment:
      PORT: ${BACKEND_PORT:-3001}
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@host.docker.internal:3306/${DATABASE_NAME}

  frontend:
    image: msoftsantana/seven-board-frontend:latest
    container_name: 7board-frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - backend

  frontend-admin:
    image: msoftsantana/seven-board-frontend-admin:latest
    container_name: 7board-frontend-admin
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - backend

networks:
  default:
    name: sevenboard_net
